# Generated by Django 4.2.4 on 2023-09-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commE', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
