# Generated by Django 4.2.4 on 2023-09-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commE', '0009_rename_first_name_order_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
