# Generated by Django 4.2.4 on 2023-09-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commE', '0011_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pin',
            new_name='zip',
        ),
    ]
